# Generated by Django 6.0.5 on 2026-05-21 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transaction', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type_transaction', models.CharField(choices=[('REVENU', 'Revenu'), ('DEPENSE', 'Dépense')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.categorie')),
            ],
        ),
    ]
